webtalk_init -webtalk_dir C:/Users/Public/Documents/PVSDRA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/cordic_module_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 11 00:23:47 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "223054df-d784-4bf8-b3c5-d1d598a77750" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fe9a41d05f22498abc16741f5405eb2f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "212" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2852 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7416_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4161827788 -regid "" -xml C:/Users/Public/Documents/PVSDRA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/cordic_module_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Public/Documents/PVSDRA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/cordic_module_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Public/Documents/PVSDRA/Lab_4/Lab_4.sim/sim_1/behav/xsim/xsim.dir/cordic_module_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
